### ISSUE TITLE
Add Build object

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/terraform-provider-tm#6]

**Comment by tzununbekov** [comment]
We didn't expose knative's build object in tm CLI so I need first add build deployment command there

**Comment by tzununbekov** [comment]
Missed the issue id in commit: https://github.com/triggermesh/terraform-provider-tm/commit/47cdc68bb7dff09201584abc2686c79447931d7a

Added build object, though right now it supports only "buildtemplate" option
